"""initial schema

Revision ID: c2b7c822e554
Revises:
Create Date: 2026-09-07 10:00:28.471941
"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.db.base  # noqa: F401 - custom column types used by autogenerate
from alembic import op

revision: str = "c2b7c822e554"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("client_secret_hash", sa.String(length=128), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("webhook_url", sa.String(length=500), nullable=True),
        sa.Column("webhook_secret", sa.String(length=128), nullable=True),
        sa.Column("allowed_flows", sa.JSON(), nullable=False),
        sa.Column("branding", sa.JSON(), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tenants_client_id"), ["client_id"], unique=True)

    op.create_table(
        "kyc_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("customer_reference", sa.String(length=128), nullable=True),
        sa.Column("flow", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("access_token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("identity", sa.JSON(), nullable=False),
        sa.Column("checks", sa.JSON(), nullable=False),
        sa.Column("internal", sa.JSON(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("completed_at", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("kyc_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_kyc_sessions_customer_reference"), ["customer_reference"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_kyc_sessions_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artifacts_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_sha256"), ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("document_hash", sa.String(length=64), nullable=True),
        sa.Column("previous_event_hash", sa.String(length=64), nullable=True),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "sequence", name="uq_audit_session_sequence"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_events_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_events_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "biometric_checks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("biometric_checks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_biometric_checks_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_biometric_checks_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "otp_challenges",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("destination_masked", sa.String(length=64), nullable=False),
        sa.Column("destination_hash", sa.String(length=64), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("verified_at", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("otp_challenges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_otp_challenges_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_otp_challenges_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("webhook_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_webhook_deliveries_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_webhook_deliveries_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("artifact_id", sa.String(length=64), nullable=False),
        sa.Column("ocr", sa.JSON(), nullable=False),
        sa.Column("verification", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("processed_at", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "signed_documents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("document_reference", sa.String(length=128), nullable=True),
        sa.Column("source_artifact_id", sa.String(length=64), nullable=False),
        sa.Column("signed_artifact_id", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("signature", sa.Text(), nullable=False),
        sa.Column("signature_algorithm", sa.String(length=64), nullable=False),
        sa.Column("certificate_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("timestamp_authority", sa.String(length=255), nullable=True),
        sa.Column("timestamp_token_artifact_id", sa.String(length=64), nullable=True),
        sa.Column("timestamped_at", app.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("timestamp_details", sa.JSON(), nullable=False),
        sa.Column("created_at", app.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["kyc_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signed_artifact_id"],
            ["artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("signed_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_signed_documents_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_signed_documents_sha256"), ["sha256"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_signed_documents_tenant_id"), ["tenant_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("signed_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signed_documents_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_signed_documents_sha256"))
        batch_op.drop_index(batch_op.f("ix_signed_documents_session_id"))

    op.drop_table("signed_documents")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_documents_session_id"))

    op.drop_table("documents")
    with op.batch_alter_table("webhook_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webhook_deliveries_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_webhook_deliveries_session_id"))

    op.drop_table("webhook_deliveries")
    with op.batch_alter_table("otp_challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_otp_challenges_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_otp_challenges_session_id"))

    op.drop_table("otp_challenges")
    with op.batch_alter_table("biometric_checks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_biometric_checks_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_biometric_checks_session_id"))

    op.drop_table("biometric_checks")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_session_id"))

    op.drop_table("audit_events")
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifacts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_artifacts_sha256"))
        batch_op.drop_index(batch_op.f("ix_artifacts_session_id"))

    op.drop_table("artifacts")
    with op.batch_alter_table("kyc_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kyc_sessions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_kyc_sessions_customer_reference"))

    op.drop_table("kyc_sessions")
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenants_client_id"))

    op.drop_table("tenants")
    # ### end Alembic commands ###
