from enum import Enum


class StrEnum(str, Enum):
    def __str__(self) -> str:
        return str(self.value)


class SessionStatus(StrEnum):
    CREATED = "CREATED"
    IN_PROGRESS = "IN_PROGRESS"
    PROCESSING = "PROCESSING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    REVIEW = "REVIEW"
    EXPIRED = "EXPIRED"


TERMINAL_STATUSES = {
    SessionStatus.VERIFIED,
    SessionStatus.REJECTED,
    SessionStatus.REVIEW,
    SessionStatus.EXPIRED,
}


class CheckStatus(StrEnum):
    PENDING = "PENDING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    REVIEW = "REVIEW"
    SKIPPED = "SKIPPED"


class Step(StrEnum):
    DOCUMENT = "DOCUMENT"
    OCR = "OCR"
    DOCUMENT_VERIFICATION = "DOCUMENT_VERIFICATION"
    SELFIE = "SELFIE"
    LIVENESS = "LIVENESS"
    FACE_MATCH = "FACE_MATCH"
    OTP = "OTP"
    SIGNATURE = "SIGNATURE"


class DocumentType(StrEnum):
    PASSPORT = "PASSPORT"
    NATIONAL_ID = "NATIONAL_ID"
    RESIDENCE_PERMIT = "RESIDENCE_PERMIT"
    DRIVING_LICENSE = "DRIVING_LICENSE"


class ArtifactKind(StrEnum):
    DOCUMENT_IMAGE = "DOCUMENT_IMAGE"
    SELFIE = "SELFIE"
    CONTRACT = "CONTRACT"
    SIGNED_CONTRACT = "SIGNED_CONTRACT"
    TIMESTAMP_TOKEN = "TIMESTAMP_TOKEN"
    AUDIT_EXPORT = "AUDIT_EXPORT"


class OtpChannel(StrEnum):
    SMS = "SMS"
    EMAIL = "EMAIL"
    WHATSAPP = "WHATSAPP"


class AuditEventType(StrEnum):
    KYC_SESSION_CREATED = "KYC_SESSION_CREATED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    OCR_COMPLETED = "OCR_COMPLETED"
    DOCUMENT_VERIFIED = "DOCUMENT_VERIFIED"
    DOCUMENT_REJECTED = "DOCUMENT_REJECTED"
    SELFIE_CAPTURED = "SELFIE_CAPTURED"
    LIVENESS_PASSED = "LIVENESS_PASSED"
    LIVENESS_FAILED = "LIVENESS_FAILED"
    FACE_MATCH_PASSED = "FACE_MATCH_PASSED"
    FACE_MATCH_FAILED = "FACE_MATCH_FAILED"
    OTP_SENT = "OTP_SENT"
    OTP_VERIFIED = "OTP_VERIFIED"
    OTP_FAILED = "OTP_FAILED"
    KYC_DECISION = "KYC_DECISION"
    CONTRACT_GENERATED = "CONTRACT_GENERATED"
    HASH_GENERATED = "HASH_GENERATED"
    DOCUMENT_SIGNED = "DOCUMENT_SIGNED"
    TIMESTAMPED = "TIMESTAMPED"
    DOCUMENT_ARCHIVED = "DOCUMENT_ARCHIVED"
    WEBHOOK_DELIVERED = "WEBHOOK_DELIVERED"
    WEBHOOK_FAILED = "WEBHOOK_FAILED"
